os:
    - linux
    - osx

language: python

python:
    - 2.7.15
    - 3.4.8
    - 3.5.5
    - 3.6.6
    - 3.7.0

before_script:
    - sudo add-apt-repository ppa:fcwu-tw/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq vim
    - pip install sh

script:
    - python tests.py
